services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mc-urban-tasks
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
